services:
  caddy:
    image: caddy:2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
